jdbc:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/root?schema=public
  username: postgres
  password: 2309
  port: 5432
  options: loglevel=1

hibernate:
  dialect: org.hibernate.dialect.PostgreSQL9Dialect
  show_sql: true
  hbm2ddl:
    auto: create

on:
  port: 3000